# Generated by Django 4.2 on 2024-10-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50, verbose_name='Город (локация)')),
                ('head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.parent', verbose_name='Старший')),
            ],
            options={
                'verbose_name': 'отделение',
                'verbose_name_plural': 'отделения',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_time', models.CharField(choices=[('сб 09:00', 'сб 09:00'), ('сб 15:00', 'сб 15:00'), ('вс 09:00', 'вс 09:00'), ('вс 15:00', 'вс 15:00')], max_length=50, verbose_name='Дата и время тренировки')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.branch', verbose_name='Отделение')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.parent', verbose_name='Наставник')),
            ],
            options={
                'verbose_name': 'отряд',
                'verbose_name_plural': 'отряды',
            },
        ),
        migrations.RemoveField(
            model_name='herostatus',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='herostatus',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='parentstatus',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='training',
            name='cell',
        ),
        migrations.AlterField(
            model_name='training',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.parent', verbose_name='Наставник'),
        ),
        migrations.DeleteModel(
            name='Cell',
        ),
        migrations.AddField(
            model_name='herostatus',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.team', verbose_name='Отряд'),
        ),
        migrations.AddField(
            model_name='parentstatus',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.branch', verbose_name='Отделение'),
        ),
        migrations.AddField(
            model_name='training',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.team', verbose_name='Отряд'),
        ),
    ]
