# Generated by Django 4.2 on 2024-10-23 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_branch_team_remove_herostatus_cell_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herostatus',
            name='type',
        ),
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.CharField(choices=[('Мощный', 'Мощный'), ('Отважный', 'Отважный'), ('Отряд мам', 'Отряд мам'), ('Пред.командир', 'Пред.командир'), ('Командир', 'Командир'), ('Выбыл', 'Выбыл')], default=0, max_length=50, verbose_name='Вид отряда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='heroes.parent', verbose_name='Наставник/Вожатая'),
        ),
    ]
