# Generated by Django 4.2 on 2024-10-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0003_remove_herostatus_type_team_type_alter_team_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Телефон'),
        ),
    ]
